// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yalla.Infrastructure.Persistence;

#nullable disable

namespace Yalla.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(YallaDbContext))]
    partial class YallaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Yalla.Domain.Audit.TableStateChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActorType")
                        .HasColumnType("int");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientCommandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DiningTableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FromStatus")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TabId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TableSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientCommandId")
                        .IsUnique()
                        .HasDatabaseName("IX_TableStateChanges_ClientCommandId");

                    b.HasIndex("BranchId", "AtUtc");

                    b.HasIndex("DiningTableId", "AtUtc");

                    b.ToTable("TableStateChanges", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Identity.DinerUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSignInAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocaleCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("PhoneE164")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneE164")
                        .IsUnique()
                        .HasDatabaseName("UX_DinerUsers_PhoneE164");

                    b.ToTable("DinerUsers", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Identity.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StaffMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("StaffMemberId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_PasswordResetTokens_TokenHash");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Identity.PhoneVerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneE164")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RequestedFromAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneE164", "ExpiresAtUtc")
                        .HasFilter("[ConsumedAtUtc] IS NULL");

                    b.ToTable("PhoneVerificationCodes", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("RotatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SubjectType")
                        .HasColumnType("int");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ChainId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_RefreshTokens_TokenHash");

                    b.HasIndex("SubjectType", "SubjectId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Identity.StaffDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BranchId", "RevokedAtUtc");

                    b.ToTable("StaffDevices", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Identity.StaffEnrolmentCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByStaffMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RedeemedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RedeemedByDeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CodeHash")
                        .IsUnique()
                        .HasDatabaseName("UX_StaffEnrolmentCodes_CodeHash");

                    b.ToTable("StaffEnrolmentCodes", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Identity.StaffSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AbsoluteExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastActivityAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RenewalTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("StaffDeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StaffMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RenewalTokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_StaffSessions_RenewalTokenHash");

                    b.HasIndex("StaffMemberId");

                    b.HasIndex("StaffDeviceId", "EndedAtUtc");

                    b.ToTable("StaffSessions", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Menus.MenuCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId", "DisplayOrder");

                    b.ToTable("MenuCategories", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Menus.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Allergens")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<Guid>("MenuCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("PortionSize")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PrepMinutes")
                        .HasColumnType("int");

                    b.Property<long>("PriceAmd")
                        .HasColumnType("bigint");

                    b.Property<int>("SpiceLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuCategoryId", "DisplayOrder");

                    b.ToTable("MenuItems", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Occupancy.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DinerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DiningTableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("GraceExtensionsUsed")
                        .HasColumnType("int");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GuestPhone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("HoldExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("LocalStartTime")
                        .HasColumnType("time");

                    b.Property<int>("PartySize")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StayHint")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("BranchId", "StartUtc");

                    b.HasIndex("DiningTableId", "StartUtc", "EndUtc");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Occupancy.TableSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DiningTableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PartySize")
                        .HasColumnType("int");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SeatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SeatedByStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<Guid?>("TabId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("IX_TableSessions_OpenByBranch")
                        .HasFilter("[ClosedAtUtc] IS NULL");

                    b.HasIndex("DiningTableId")
                        .IsUnique()
                        .HasDatabaseName("UX_TableSessions_OpenPerTable")
                        .HasFilter("[ClosedAtUtc] IS NULL");

                    b.HasIndex("ReservationId");

                    b.HasIndex("SeatedByStaffId");

                    b.HasIndex("DiningTableId", "SeatedAtUtc");

                    b.ToTable("TableSessions", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Staff.StaffMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("PinFailedAttempts")
                        .HasColumnType("int");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("PinLockedUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_StaffMembers_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("VenueId", "IsActive");

                    b.ToTable("StaffMembers", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Tabs.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AmountAmd")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TabId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TabParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProviderReference");

                    b.HasIndex("TabParticipantId");

                    b.HasIndex("TabId", "Status");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Tabs.Tab", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DiningTableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HideTotalFromGuests")
                        .HasColumnType("bit");

                    b.Property<Guid?>("HostParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("PaidAmd")
                        .HasColumnType("bigint");

                    b.Property<long>("RemainingAmd")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("ServiceChargeAmd")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ServiceChargePercentSnapshot")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("SettlementMode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SettlementModeLockedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("SubtotalAmd")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TableSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("TotalAmd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DiningTableId");

                    b.HasIndex("TableSessionId");

                    b.HasIndex("BranchId", "Status");

                    b.ToTable("Tabs", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Tabs.TabJoinToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TabId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("TabId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("TabJoinTokens", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Tabs.TabOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlacedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PlacedByParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PlacedByStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TabId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlacedByParticipantId");

                    b.HasIndex("PlacedByStaffId");

                    b.HasIndex("TabId", "Status");

                    b.ToTable("TabOrders", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Tabs.TabOrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsShared")
                        .HasColumnType("bit");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("TabOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("UnitPriceAmdSnapshot")
                        .HasColumnType("bigint");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("VoidedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("VoidedByStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("TabOrderId");

                    b.HasIndex("VoidedByStaffId");

                    b.ToTable("TabOrderLines", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Tabs.TabOrderLineShare", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TabOrderLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TabParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TabParticipantId");

                    b.HasIndex("TabOrderLineId", "TabParticipantId")
                        .IsUnique();

                    b.ToTable("TabOrderLineShares", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Tabs.TabParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CanOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("CanPay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("CanSeeTableTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RemovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TabId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TabId", "DeviceId");

                    b.HasIndex("TabId", "Status");

                    b.ToTable("TabParticipants", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Venues.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("FloorHeight")
                        .HasColumnType("int");

                    b.Property<int>("FloorWidth")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VenueId", "Slug")
                        .IsUnique();

                    b.ToTable("Branches", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Venues.DiningTable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurrentSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FloorAreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBookable")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("QrToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<double>("RotationDegrees")
                        .HasColumnType("float");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<int>("Shape")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FloorAreaId");

                    b.HasIndex("QrToken")
                        .IsUnique();

                    b.HasIndex("BranchId", "Label")
                        .IsUnique();

                    b.HasIndex("BranchId", "Status");

                    b.ToTable("DiningTables", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Venues.FloorArea", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId", "DisplayOrder");

                    b.ToTable("FloorAreas", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Venues.OpeningHours", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("ClosesAt")
                        .HasColumnType("time");

                    b.Property<bool>("ClosesNextDay")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("OpensAt")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("BranchId", "Day");

                    b.ToTable("OpeningHours", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Venues.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Venues", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Audit.TableStateChange", b =>
                {
                    b.HasOne("Yalla.Domain.Venues.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yalla.Domain.Venues.DiningTable", "DiningTable")
                        .WithMany()
                        .HasForeignKey("DiningTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("DiningTable");
                });

            modelBuilder.Entity("Yalla.Domain.Identity.PasswordResetToken", b =>
                {
                    b.HasOne("Yalla.Domain.Staff.StaffMember", "StaffMember")
                        .WithMany()
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaffMember");
                });

            modelBuilder.Entity("Yalla.Domain.Identity.StaffDevice", b =>
                {
                    b.HasOne("Yalla.Domain.Venues.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Yalla.Domain.Identity.StaffEnrolmentCode", b =>
                {
                    b.HasOne("Yalla.Domain.Venues.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Yalla.Domain.Identity.StaffSession", b =>
                {
                    b.HasOne("Yalla.Domain.Identity.StaffDevice", "StaffDevice")
                        .WithMany()
                        .HasForeignKey("StaffDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yalla.Domain.Staff.StaffMember", "StaffMember")
                        .WithMany()
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StaffDevice");

                    b.Navigation("StaffMember");
                });

            modelBuilder.Entity("Yalla.Domain.Menus.MenuCategory", b =>
                {
                    b.HasOne("Yalla.Domain.Venues.Branch", "Branch")
                        .WithMany("MenuCategories")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Yalla.Domain.Menus.MenuItem", b =>
                {
                    b.HasOne("Yalla.Domain.Menus.MenuCategory", "MenuCategory")
                        .WithMany("Items")
                        .HasForeignKey("MenuCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuCategory");
                });

            modelBuilder.Entity("Yalla.Domain.Occupancy.Reservation", b =>
                {
                    b.HasOne("Yalla.Domain.Venues.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yalla.Domain.Venues.DiningTable", "DiningTable")
                        .WithMany()
                        .HasForeignKey("DiningTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("DiningTable");
                });

            modelBuilder.Entity("Yalla.Domain.Occupancy.TableSession", b =>
                {
                    b.HasOne("Yalla.Domain.Venues.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yalla.Domain.Venues.DiningTable", "DiningTable")
                        .WithMany()
                        .HasForeignKey("DiningTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yalla.Domain.Occupancy.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yalla.Domain.Staff.StaffMember", "SeatedByStaff")
                        .WithMany()
                        .HasForeignKey("SeatedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("DiningTable");

                    b.Navigation("Reservation");

                    b.Navigation("SeatedByStaff");
                });

            modelBuilder.Entity("Yalla.Domain.Staff.StaffMember", b =>
                {
                    b.HasOne("Yalla.Domain.Venues.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yalla.Domain.Venues.Venue", "Venue")
                        .WithMany("Staff")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Yalla.Domain.Tabs.Payment", b =>
                {
                    b.HasOne("Yalla.Domain.Tabs.Tab", "Tab")
                        .WithMany("Payments")
                        .HasForeignKey("TabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yalla.Domain.Tabs.TabParticipant", "TabParticipant")
                        .WithMany()
                        .HasForeignKey("TabParticipantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tab");

                    b.Navigation("TabParticipant");
                });

            modelBuilder.Entity("Yalla.Domain.Tabs.Tab", b =>
                {
                    b.HasOne("Yalla.Domain.Venues.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yalla.Domain.Venues.DiningTable", "DiningTable")
                        .WithMany()
                        .HasForeignKey("DiningTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yalla.Domain.Occupancy.TableSession", "TableSession")
                        .WithMany()
                        .HasForeignKey("TableSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("DiningTable");

                    b.Navigation("TableSession");
                });

            modelBuilder.Entity("Yalla.Domain.Tabs.TabJoinToken", b =>
                {
                    b.HasOne("Yalla.Domain.Tabs.Tab", "Tab")
                        .WithMany("JoinTokens")
                        .HasForeignKey("TabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tab");
                });

            modelBuilder.Entity("Yalla.Domain.Tabs.TabOrder", b =>
                {
                    b.HasOne("Yalla.Domain.Tabs.TabParticipant", "PlacedByParticipant")
                        .WithMany()
                        .HasForeignKey("PlacedByParticipantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yalla.Domain.Staff.StaffMember", "PlacedByStaff")
                        .WithMany()
                        .HasForeignKey("PlacedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yalla.Domain.Tabs.Tab", "Tab")
                        .WithMany("Orders")
                        .HasForeignKey("TabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlacedByParticipant");

                    b.Navigation("PlacedByStaff");

                    b.Navigation("Tab");
                });

            modelBuilder.Entity("Yalla.Domain.Tabs.TabOrderLine", b =>
                {
                    b.HasOne("Yalla.Domain.Menus.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yalla.Domain.Tabs.TabOrder", "TabOrder")
                        .WithMany("Lines")
                        .HasForeignKey("TabOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yalla.Domain.Staff.StaffMember", "VoidedByStaff")
                        .WithMany()
                        .HasForeignKey("VoidedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MenuItem");

                    b.Navigation("TabOrder");

                    b.Navigation("VoidedByStaff");
                });

            modelBuilder.Entity("Yalla.Domain.Tabs.TabOrderLineShare", b =>
                {
                    b.HasOne("Yalla.Domain.Tabs.TabOrderLine", "TabOrderLine")
                        .WithMany("Shares")
                        .HasForeignKey("TabOrderLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yalla.Domain.Tabs.TabParticipant", "TabParticipant")
                        .WithMany()
                        .HasForeignKey("TabParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TabOrderLine");

                    b.Navigation("TabParticipant");
                });

            modelBuilder.Entity("Yalla.Domain.Tabs.TabParticipant", b =>
                {
                    b.HasOne("Yalla.Domain.Tabs.Tab", "Tab")
                        .WithMany("Participants")
                        .HasForeignKey("TabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tab");
                });

            modelBuilder.Entity("Yalla.Domain.Venues.Branch", b =>
                {
                    b.HasOne("Yalla.Domain.Venues.Venue", "Venue")
                        .WithMany("Branches")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Yalla.Domain.Venues.ReservationPolicy", "ReservationPolicy", b1 =>
                        {
                            b1.Property<Guid>("BranchId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("ApprovalRequiredAbovePartySize")
                                .HasColumnType("int");

                            b1.Property<bool>("AutoConfirm")
                                .HasColumnType("bit");

                            b1.Property<int>("BookingWindowDays")
                                .HasColumnType("int");

                            b1.Property<int>("BufferMinutes")
                                .HasColumnType("int");

                            b1.Property<int>("CancellationDeadlineMinutes")
                                .HasColumnType("int");

                            b1.Property<int>("GraceExtensionMinutes")
                                .HasColumnType("int");

                            b1.Property<int>("GraceMinutes")
                                .HasColumnType("int");

                            b1.Property<int>("LateNudgeAfterMinutes")
                                .HasColumnType("int");

                            b1.Property<int?>("MaxSeatOverhang")
                                .HasColumnType("int");

                            b1.Property<int>("MinLeadMinutes")
                                .HasColumnType("int");

                            b1.Property<bool>("PricesIncludeVat")
                                .HasColumnType("bit");

                            b1.Property<decimal>("ServiceChargePercent")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<int>("TurnTimeMinutes")
                                .HasColumnType("int");

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.Navigation("ReservationPolicy")
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Yalla.Domain.Venues.DiningTable", b =>
                {
                    b.HasOne("Yalla.Domain.Venues.Branch", "Branch")
                        .WithMany("DiningTables")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yalla.Domain.Venues.FloorArea", "FloorArea")
                        .WithMany("DiningTables")
                        .HasForeignKey("FloorAreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("FloorArea");
                });

            modelBuilder.Entity("Yalla.Domain.Venues.FloorArea", b =>
                {
                    b.HasOne("Yalla.Domain.Venues.Branch", "Branch")
                        .WithMany("FloorAreas")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Yalla.Domain.Venues.OpeningHours", b =>
                {
                    b.HasOne("Yalla.Domain.Venues.Branch", "Branch")
                        .WithMany("OpeningHours")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Yalla.Domain.Menus.MenuCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Yalla.Domain.Tabs.Tab", b =>
                {
                    b.Navigation("JoinTokens");

                    b.Navigation("Orders");

                    b.Navigation("Participants");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Yalla.Domain.Tabs.TabOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Yalla.Domain.Tabs.TabOrderLine", b =>
                {
                    b.Navigation("Shares");
                });

            modelBuilder.Entity("Yalla.Domain.Venues.Branch", b =>
                {
                    b.Navigation("DiningTables");

                    b.Navigation("FloorAreas");

                    b.Navigation("MenuCategories");

                    b.Navigation("OpeningHours");
                });

            modelBuilder.Entity("Yalla.Domain.Venues.FloorArea", b =>
                {
                    b.Navigation("DiningTables");
                });

            modelBuilder.Entity("Yalla.Domain.Venues.Venue", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
