namespace Yalla.Application.Tables;

/// <summary>
/// Fields every state-change command carries.
/// </summary>
/// <remarks>
/// <see cref="ClientCommandId"/> is generated by the caller, not the server. The staff tablet
/// queues changes while the cafe wifi is down and replays them on reconnect, so the same command
/// arrives twice; the id is what lets the second arrival be recognised and answered with the
/// first one's result.
/// </remarks>
public interface ITableStateCommand
{
    Guid BranchId { get; }

    Guid TableId { get; }

    /// <summary>Caller-generated id. A replay with the same value is a no-op.</summary>
    Guid ClientCommandId { get; }

    /// <summary>Free text for the audit log. Defaulted per transition when omitted.</summary>
    string? Reason { get; }
}

/// <summary>A transition that needs nothing beyond the table itself.</summary>
public sealed record TableStateCommand(
    Guid BranchId,
    Guid TableId,
    Guid ClientCommandId,
    string? Reason = null) : ITableStateCommand;

/// <summary>Seat a party with no booking. The common case in a cafe.</summary>
public sealed record SeatWalkInCommand(
    Guid BranchId,
    Guid TableId,
    int PartySize,
    Guid ClientCommandId,
    string? Reason = null) : ITableStateCommand;

/// <summary>
/// Seat a party against their booking, which also moves the booking to Seated. <c>PartySize</c>
/// overrides the booked size when the number who turned up differs.
/// </summary>
public sealed record SeatReservationCommand(
    Guid BranchId,
    Guid TableId,
    Guid ReservationId,
    Guid ClientCommandId,
    int? PartySize = null,
    string? Reason = null) : ITableStateCommand;

/// <summary>
/// Seat the party a hold was placed for. <see cref="ReservationId"/> is set when the hold was
/// for a late booking, which is the usual reason to hold a table.
/// </summary>
public sealed record SeatHeldPartyCommand(
    Guid BranchId,
    Guid TableId,
    int PartySize,
    Guid ClientCommandId,
    Guid? ReservationId = null,
    string? Reason = null) : ITableStateCommand;

/// <summary>Write off an outstanding balance. Manager-only.</summary>
public sealed record AbandonTabCommand(
    Guid BranchId,
    Guid TabId,
    Guid ClientCommandId,
    string? Reason = null);
